### ISSUE TITLE
MAC Address Not Working As Environment Variable When Using Docker Compose

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [mariusmotea/diyHue#338]
I am trying to keep all of my Docker Containers in a Docker Compose file to simplify machine reinstall and scaling.

I have ported over the suggested installation parameters to compose:

```
  diyhue:
    image: cheesemarathon/diyhue:latest
    container_name: diyhue
    restart: unless-stopped
    ports:
      - target: 1900
        published: 1900
        protocol: udp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ${USERDIR}/docker/diyhue/export:/opt/hue-emulator/export:rw
    environment:
      - MAC=XX:XX:XX:XX:XX:XX
```

MAC address has been anonymised using X's for the purpose of raising this issue.

All appears to pull and run correctly however, when investigating the logs, the script is still using the script of the container instead of the one provided in Compose.

Any assistance on getting this to work would be greatly appreciated!

**Comment by cheesemarathon** [comment]
That environmental variable is no longer needed. So long as you run the container with the host network setting. The container will detect the host MAC address itself

**Comment by cheesemarathon** [comment]
In fact, if it's in host mode, you don't even need to publish those ports.

**Comment by cheesemarathon** [comment]
It looks like you may want to set [this](https://docs.docker.com/compose/compose-file/#network_mode) variable in your compose YAML file

**Comment by danieledwardgeorgehitchcock** [comment]
Correct me if I am wrong, but using the host setting removes a lot of the control about how network traffic, etc moves through docker..?

I am running a Traefik load balancer / reverse proxy in front of my setup and this setup would not work well with such a product.

I know that the ports need to be set to what they are in order to work with Hue but I'd rather avoid blindly mapping to host..

Can the Environment Variable be re-added to the dockerfile and if one isn't provided, a default of the MAC found is used?

This would add the greatest flexibility to the Dockerised DIYHue..

**Comment by cheesemarathon** [comment]
I can look into this but it may take a few days.. This was the plan originally but we were unable to get the hue app to detect the emulated hue if it was not in host mode, even with the above ports mapped. But we have made quite a few other changes since then so I'll give it a go, we may have been missing something else!

**Comment by danieledwardgeorgehitchcock** [comment]
Yeah thats fine!

I am not demanding that it SHOULD be fixed.. this is an open source project after all, and I could always contribute to it (if I knew what I was talking about)!

I appreciate all the hard work that has been done so far and a Docker image is the icing on the cake :-)

Let me know if there is anything I can test!

**Comment by cheesemarathon** [comment]
We have something working. Just making sure that Marius is happy with the changes before making them public. You will optionally be able to provide host MAC and IP variables when using the container in bridge network mode.

**Comment by cheesemarathon** [comment]
Ok, this should be fixed now with the latest container images. Here is a compose file that should now work. You just need to set your MAC and IP

```
 diyhue:
    image: cheesemarathon/diyhue:latest
    container_name: diyhue
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 1900
        published: 1900
        protocol: udp
        mode: host
      - target: 2100
        published: 2100
        protocol: udp
        mode: host
    volumes:
      - ${USERDIR}/docker/diyhue/export:/opt/hue-emulator/export:rw
    environment:
      - MAC=XX:XX:XX:XX:XX:XX
      - IP=XX.XX.XX.XX
```
Let me know how you get on with that. If it works, please close this issue.
Thanks
