### ISSUE TITLE
Push button doesn't wprk

### ISSUE THREAD

**Issue by dmratcliffe** [mariusmotea/diyHue#422]
**Describe the bug**
The hue app (official) finds the hue but the link button ("activate") does not allow the connection

**To Reproduce**
1. Download the repository
2. Modify the docker compose to:
```
version: '2'
services:
  diyHue:
    image: diyhue/core:amd64
    restart: always
    volumes:
      - ../exports:/opt/hue-emulator/export
    ports:
      - "80:80"
```
3. Open default hue app
4. Hue app finds fake hub
5. Hue app asks to click the link button
6. Click activate in the link panel
7. Nothing happens, no link is made.

**Expected behavior**
Hue app discovers hue and the push button pairs with the hue

**Logs**
Nothing seems to appear in the logs

**Docker Info (please complete the following information):**
 - Architecture: amd64
 - Docker image version: amd64
 - Hardware: PC, (Moby Linux docker image)

**Comment by mariusmotea** [comment]
Try to wipe data of the hue application, or just reinstall it. I believe it cache the certificate of previews tries and now deny the new one.

**Comment by dmratcliffe** [comment]
I was working remotely using the desktop hue app, it appears I got it to work. I can't say for sure but it looks like it happened right after I added more ports to the docker-compose. I'll confirm this is the case when I get home one sunday.

This is the changed config:
```
version: '2'
services:
  diyHue:
    image: diyhue/core:amd64
    restart: always
    volumes:
      - ../exports:/opt/hue-emulator/export
    ports:
      - "80:80"
      - "443:443"
      - "1900:1900"
      - "2100:2100"
```

**Comment by dmratcliffe** [comment]
@mariusmotea it seems to fail, in person, with the offical app. I can use hue essentials to connect and control bulbs. (I would like the offical app more though) any thoughts?

**Comment by mariusmotea** [comment]
From wiki

docker run -d --name "diyHue" --network="bridge" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' -e 'MAC=XX:XX:XX:XX:XX:XX' -e 'IP=XX.XX.XX.XX' -p 80:80/tcp -p 443:443/tcp -p 1900:1900/udp -p 2100:2100/udp diyhue/core:latest

So you need to set IP and MAC variables in compose manifest.

**Comment by cheesemarathon** [comment]
Your docker compose file should be this:
```
version: '2'
services:
  diyHue:
    image: diyhue/core:latest
    restart: always
    volumes:
      - ../exports:/opt/hue-emulator/export
    ports:
      - "80:80"
      - "443:443"
      - "1900:1900"
      - "2100:2100"
    environment:
      - "MAC=XX:XX:XX:XX:XX:XX"
      - "IP=XX.XX.XX.XX"
```
You will need to delete any certificate file from `../exports` before running this compose file. Don't forget to change the MAC and IP variables above to your correct values for your docker host. Finally do a factory reset on the hue app after recreating your diyHue docker container. On iOS just reinstall the app, on Android go to `Settings-Apps-Hue-Storage` then click `Clear storage`. Also notice how I have changed the image used in your compose file. This image should auto pull the latest image for your system architecture. Reopen this if you have any more issues but this should fix everything for you.

**Comment by cheesemarathon** [comment]
ah just remembered that your running this on windows. You may need to use the `diyhue/core:amd64` you were originally using instead of my suggest. If it fails to pull, that should fix it.

**Comment by dmratcliffe** [comment]
With this as my config:
```
version: '2'
services:
  diyHue:
    image: diyhue/core:latest
    restart: always
    volumes:
      - ../exports:/opt/hue-emulator/export
    ports:
      - "80:80"
      - "443:443"
      - "1900:1900"
      - "2100:2100"
    environment:
      - "MAC=fe80::6c4f:b802:335:eb4d"
      - "IP=192.168.1.99"
```

The first time it generates the cert it gives this error in the log:
```
diyHue_1  | MAC given as 'fe80::6c4f:b802:335:eb4d'
diyHue_1  | --Setting up diyHue--
diyHue_1  | --Generating certificate--
diyHue_1  | MAC passed as 'fe80::6c4f:b802:335:eb4d'
diyHue_1  | --Host MAC address is fe80::6c4f:b802:335:eb4d--
diyHue_1  | Traceback (most recent call last):
diyHue_1  |   File "<string>", line 1, in <module>
diyHue_1  | ValueError: invalid literal for int() with base 16: 'fe0:6cfffef:80:3'
diyHue_1  | req: Option -set_serial needs a value
diyHue_1  | req: Use -help for summary.
diyHue_1  | cat: private.key: No such file or directory
diyHue_1  | cat: public.crt: No such file or directory
diyHue_1  | rm: cannot remove 'private.key': No such file or directory
diyHue_1  | rm: cannot remove 'public.crt': No such file or directory
diyHue_1  | --Certificate created--
diyHue_1  | --Restoring config--
diyHue_1  | --Config restored--
diyHue_1  | --Startup complete. Open Hue app and search for bridges--
diyHue_1  | Starting with provided MAC & IP
```

The hue app finds the hub but fails to connect with the link button still
